server:
  port: 6060

spring:
  profiles:
    active: dev
  application:
    name: constructing-composite-indicators
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/composite_indicator?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: root